### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by unnnyong** [unnnyong/iOS-and-Ruby#1]
비공개로 돌려야하나? 우선은 이걸로 시작 !

- [ ] 틀만 있는 ppt 만들기.
- [ ] repository 만들기.
- [ ] 코드 테스트
- [ ] 테스트 내용  ppt 에 넣기.
- [ ] 대본
- [ ] ppt 디자인까지 확실히 !

**Comment by unnnyong** [comment]
### tachikoma

**Comment by unnnyong** [comment]
## tachikoma


### tachikoma란?

![image](https://user-images.githubusercontent.com/28520053/46804748-6c483b00-cd9e-11e8-9b8d-89360ffba1b0.png)

- 공각기동대 STAND ALONE COMPLEX 시리즈에 등장하는 인공지능(思考) 소형 다각 전차.

**Comment by unnnyong** [comment]
## houston 
### houston 이란?

**Comment by unnnyong** [comment]
## 🔮Ruby와 Gem

**Comment by unnnyong** [comment]
## danger

### danger란?
- Stop saying "you forgot to …" in code review
- Danger runs after your CI, automating your team's conventions surrounding code review.
- 사람이 은근 실수하는 것들을 `danger 파일`에 등록해 놓으면, 풀리퀘스트를 올리면 등록한 내용에 대해 코드 리뷰를 
해준다.
    - 예 ) Swift화가 진행되고 있는 중인 제가 담당하고 있는 서비스에서는 Objc 와 Swift 에서 코드 내용은 공통적으로 하고 공개 설정이 다른 함수가 있는데 스위프트 파일에서는 ForObjc가 있는 파일이 있으면 코드리뷰에서 필터링 되도록 설정해두고 있어요 

### 그래서 어떻게 사용하나?

**Comment by unnnyong** [comment]
## danger

### danger란?
- Stop saying "you forgot to …" in code review
- Danger runs after your CI, automating your team's conventions surrounding code review.
- 사람이 은근 실수하는 것들을 `danger 파일`에 등록해 놓으면, 풀리퀘스트를 올리면 등록한 내용에 대해 코드 리뷰를 
해준다.
    - 예 ) Swift화가 진행되고 있는 중인 제가 담당하고 있는 서비스에서는 Objc 와 Swift 에서 코드 내용은 공통적으로 하고 공개 설정이 다른 함수가 있는데 스위프트 파일에서는 ForObjc가 있는 파일이 있으면 코드리뷰에서 필터링 되도록 설정해두고 있어요 
- 우리 팀에서는 여기에 SwiftLint, SwiftFormat 까지 사용하고 있다는 사실 👍 
    - 이 얘기는 Objc 의 코드 수정은 아직도 현재 진행 중. 그 수정이 SwiftLint, SwiftFormat에서 커버되지 않아서 (특히 팀 내의 코드 스타일의 경우) danger에 수동으로 넣어넣고 자동으로 코드리뷰를 받음으로써 사람의 코멘트를 그나마 줄일 수 있다.

### 그래서 어떻게 사용하나?


참고
-

**Comment by unnnyong** [comment]
## tenma

### tenma란?
- ...

### 그래서 어떻게 사용하나?

- ...

참고
- ...

**Comment by unnnyong** [comment]
## fastlane

### fastlane란?
- ...

### 그래서 어떻게 사용하나?

- ...

참고
- ...

**Comment by unnnyong** [comment]
https://tech.mercari.com/entry/2017/12/21/143000
